# Generated by Django 4.1.7 on 2023-03-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20200926_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calorie', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PostExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_amount', models.FloatField(blank=True, default=0, null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='all_exercises_selected_today',
            field=models.ManyToManyField(related_name='inventory', through='calories.PostExercise', to='calories.exercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='exercise_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calories.exercise'),
        ),
    ]
