# Generated by Django 4.1.7 on 2023-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_rename_calorie_amount_postexercise_calorie_lost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postexercise',
            old_name='calorie_lost',
            new_name='calorie_burned',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
