# Generated by Django 4.1.7 on 2023-03-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0009_alter_profile_all_exercises_selected_today'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_calories_burned',
            new_name='total_calorie_burned',
        ),
    ]
