# Generated by Django 4.1.7 on 2023-03-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0013_alter_profile_person_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
    ]
